
/* ALTERAR OS DADOS PARA A ESTAÇÃO DE ACORDO COM AS CONFIGURAÇÕES DO AP */
const char ESSID[32] = "REDE"; // SSID DA REDE NO AP
const char PASSWD[64] = "SENHA"; // SENHA DA REDE
const char* MQTT_IP = "192.168.0.11"; // ENDEREÇO DO SMARTPHONE QUE EXECUTA O MOSQUITTO

// NOME DA ESTAÇÃO EX:. 01, O2, 03, ...
char DEVICE_LABEL[4] = "01"; 

/* PINO DO LED PARA O ESP-01S*/
static const uint8_t BlUE_LED = 2;

/* O LED AZUL DO MÓDULO ESP-01 ESTÁ CONECTADO AO GPIO1 (QUE TAMBÉM É O TXD, PORTANTO, 
NÃO É POSSÍVEL IMPRIMIR Serial.print() COM O PINO 1 JÁ HABILITADO PARA O LED 
PINO DO LED PARA O ESP-01, TAMBÉM COMENTAR A LINHA Serial.begin(115200) EM setup()*/
//static const uint8_t BlUE_LED = 1;
